### PR TITLE
DM-21161: AuxTel on-sky testing round 2

### PR DESCRIPTION
**Pull request by tribeiro**
Fix ATPneumatics enumerations to be compatible with the values stablished on the component. This need to be fixed in the xml as well.

### CODE REVIEW

**Review by r-owen — CHANGES_REQUESTED** [review]
Sorry, but these need to be uppercase.

Some values just can't be CamelCase so we make them all UPPERCASE. You can choose whether to use underscores to separate words or not.

**Comment by r-owen** [comment]
By the way: the pull request description says ATMCS but the code seems to be ATPneumatics. If you don't mind fixing the pull request description...

**Comment by tribeiro** [comment]
Done and done...

**Review by r-owen — APPROVED** [review]
Looks fine. I am unhappy about summary states leaking into other states, but the real code works that way so we have no choice.

**Pull request merged**
